"""Lumine method style — chunked action text format + paired parser.

Structure mirrors arxiv:2511.08892 §4 (Keyboard-and-Mouse Modelling):

  - pacing line       : "Plan the next action sequence, consisting of N steps..."
  - action template   : ``<|action_start|>X Y Z ; k1 k2 k3 ; k4 k5 ; ...<|action_end|>``
  - explanation       : numbered rules for mouse / keys / output hygiene

Each segment is generated by its own ``render_*`` method so the four
decoupling knobs only touch one place each:

  - ``thinking``    — toggles the "describe your plan first" wording in explanation
  - ``mouse``       — toggles the `X Y Z` prefix everywhere
  - ``chunk_steps`` — number of key groups (adapter's value wins if published)
  - ``key_bindings`` — handled upstream by the adapter / composer, not here
"""

from __future__ import annotations

import re
from dataclasses import dataclass

from .base import MethodStyle
from omni_game_arena.utils.mouse_calibration import degrees_to_mouse_units

CHUNK_STEPS = 8  # default chunk length

USER_PROMPT = "Based on the current game screen, plan your next actions."


def _looks_like_bare_action_line(
    line: str,
    *,
    mouse_axes: tuple[str, ...],
) -> bool:
    parts = line.split(';')
    if len(parts) < 2:
        return False

    if mouse_axes:
        mouse_tokens = parts[0].strip().split()
        if len(mouse_tokens) < len(mouse_axes):
            return False
        for token in mouse_tokens[:len(mouse_axes)]:
            try:
                float(token)
            except ValueError:
                return False

    return any(part.strip() for part in parts[1:])


def _extract_action_content(
    text: str,
    *,
    mouse_axes: tuple[str, ...],
) -> str | None:
    match = re.search(
        r'<\|action_start\|[>}](.*?)<\|action_end\|[>}]', text, re.DOTALL
    )
    if match is not None:
        return match.group(1).strip()

    # Some models omit the action tags but still put a valid chunked action
    # on its own line. Accept only that narrow fallback shape.
    for raw_line in reversed(text.splitlines()):
        line = raw_line.strip()
        if _looks_like_bare_action_line(line, mouse_axes=mouse_axes):
            return line

    return None


def parse_chunked_action(
    text: str,
    *,
    chunk_steps: int = CHUNK_STEPS,
    mouse_axes: tuple[str, ...] = ("X", "Y", "Z"),
) -> dict | None:
    """Parse Lumine-style action string.

    The mouse prefix contains exactly ``len(mouse_axes)`` tokens, in the
    order the axes are listed. X/Y tokens are emitted by the VLM in
    degrees, then converted to UE mouse units for execution. The returned
    ``"mouse"`` field is always a 3-tuple ``(dx, dy, scroll)``; axes not
    in ``mouse_axes`` are 0.
    ``"mouse_output"`` preserves the VLM-facing values for compact logs.
    ``"mouse_axes"`` records the original prompt axes so recorders can
    write the same prefix length back out.

    Examples:
      mouse_axes=("X", "Y", "Z") → expects ``X Y Z ; k1 ; ...``
      mouse_axes=("X",)          → expects ``X ; k1 ; ...``
      mouse_axes=()              → expects ``k1 ; ...``

    Returns ``{"mouse": (dx, dy, scroll), "mouse_output": (...),
    "mouse_axes": (...), "steps": [[...], ...]}`` or ``None`` on failure.
    """
    extracted_content = _extract_action_content(text, mouse_axes=mouse_axes)
    if extracted_content is None:
        return None
    text = f"<|action_start|>{extracted_content}<|action_end|>"

    # Tolerate a common Claude typo where the closing `>` of `<|action_start|>`
    # is sometimes emitted as `}` (likely token-boundary noise around `|>`).
    # Once that typo enters the in-episode history the model copies it on
    # subsequent turns, so a single mis-token cascades into a string of noop
    # actions. Accept both `>` and `}` to keep the run alive.
    match = re.search(
        r'<\|action_start\|[>}](.*?)<\|action_end\|[>}]', text, re.DOTALL
    )
    if match is None:
        # No action tag in the response. Don't fall back to splitting raw
        # text on ``;`` — that silently produces an all-empty chunk plan
        # and the agent walks in place. Treat it as a parse failure so
        # the caller logs the raw response and emits a real no-op.
        return None
    content = match.group(1).strip()

    if not content:
        return None

    parts = content.split(';')

    axis_vals = {"X": 0.0, "Y": 0.0, "Z": 0.0}
    output_vals = {"X": 0.0, "Y": 0.0, "Z": 0.0}
    if mouse_axes:
        if len(parts) < 2:
            return None
        mouse_tokens = parts[0].strip().split()
        for i, axis in enumerate(mouse_axes):
            try:
                output_val = float(mouse_tokens[i]) if i < len(mouse_tokens) else 0.0
            except ValueError:
                output_val = 0.0
            output_vals[axis] = output_val
            axis_vals[axis] = (
                degrees_to_mouse_units(output_val)
                if axis in ("X", "Y")
                else output_val
            )
        key_start = 1
    else:
        key_start = 0

    steps: list[list[str]] = []
    for i in range(chunk_steps):
        idx = key_start + i
        if idx < len(parts):
            keys_str = parts[idx].strip()
            keys = keys_str.split() if keys_str else []
        else:
            keys = []
        steps.append(keys)

    return {
        "mouse": (axis_vals["X"], axis_vals["Y"], axis_vals["Z"]),
        "mouse_output": (output_vals["X"], output_vals["Y"], output_vals["Z"]),
        "mouse_axes": tuple(mouse_axes),
        "steps": steps,
    }


def is_empty_action(action: dict | None) -> bool:
    """True iff the parsed action carries no mouse motion AND no key in any step.

    Lumine occasionally produces ``<|action_start|>;;;;<|action_end|>`` —
    syntactically valid but semantically a no-op. The caller treats this
    the same as a parse failure so the raw response gets logged.
    """
    if not action:
        return True
    mouse = action.get("mouse") or ()
    if any(v != 0 for v in mouse):
        return False
    for step_keys in action.get("steps") or []:
        if step_keys:
            return False
    return True


@dataclass
class LumineStyle(MethodStyle):
    name: str = "lumine"
    # History layout. Two valid values:
    #   "packed" — every history frame + the current frame go into ONE user
    #              message, with a compact `[action t-N]: <tag>` list at the
    #              bottom. The Lumine paper's original recipe; cheapest token
    #              footprint but unnatural for chat models.
    #   "turns"  — each past (frame, full-reasoning) pair becomes its own
    #              user/assistant turn. More natural for Claude/GPT/Qwen-VL,
    #              prompt-cache friendly. Risk: past assistant reasoning can
    #              anchor the model into repeating its own previous moves.
    # Default is "turns" — switched from "packed" because chat-tuned VLMs
    # appear to follow visual context more cleanly when history is laid out
    # as a real dialogue rather than as one packed multi-image user turn.
    history_layout: str = "turns"
    thinking: bool = True
    # Which mouse axes appear in the action format. Ordered tuple so the
    # prompt renders axes in the same order the parser reads them back.
    # Empty tuple → no mouse prefix. The adapter's ``mouse_axes`` (via
    # ``action_schema``) overrides this at render time when it differs.
    mouse_axes: tuple[str, ...] = ("X", "Y", "Z")
    chunk_steps: int = CHUNK_STEPS

    # Class-level (no annotation so dataclass ignores it).
    # Cycling group-size pattern from Lumine paper example:
    # "k1 k2 k3 ; k4 k5 ; k6 ; k7 ; k8 ; k9 k10" — demonstrates that each
    # group can hold multiple keys and that lengths vary.
    _GROUP_SIZES = (3, 2, 1, 1, 1, 2)

    # ── Per-part renderers ────────────────────────────────────────────

    def render_pacing(self, chunk: int, _step_ms: int) -> str:
        # Lumine paper §4 originally placed a "pacing line" here, e.g.
        # "Plan the next action sequence as 6 consecutive steps, based on
        # the current game screen." That sentence is now empty by default
        # because every word of it is already covered elsewhere:
        #   - "based on the current game screen, plan your next actions"
        #     is the per_turn_user_text() sent with every user turn;
        #   - "6 consecutive steps" is implied by the action template
        #     showing 6 `;`-separated groups, and stated explicitly in the
        #     render_explanation() section right below ("Key Sequence: N
        #     groups separated by `;`").
        # Subclasses that want the original Lumine pacing back can override.
        return ""

    def render_action_template(self, chunk: int) -> str:
        keys = self._keys_template(chunk)
        if self.mouse_axes:
            mouse_prefix = " ".join(self.mouse_axes) + " ; "
        else:
            mouse_prefix = ""
        lines = ["Output Format"]
        rotation_axes = [axis for axis in self.mouse_axes if axis in ("X", "Y")]
        if rotation_axes:
            axis_label = "/".join(rotation_axes)
            lines.append(
                f"Mouse rotation values {axis_label} are degrees, not raw mouse units."
            )
        lines.append(f"<|action_start|>{mouse_prefix}{keys}<|action_end|>")
        return "\n".join(lines)

    def render_explanation(self, chunk: int) -> str:
        lines = ["Explanation"]
        idx = 1
        mouse_desc = self._render_mouse_description()
        if mouse_desc:
            lines.append(f"{idx}. Mouse Movement: {mouse_desc}")
            idx += 1
        if chunk > 1:
            key_header = (
                f"Key Sequence: {chunk} groups separated by `;`. In the "
                "template above, each `k_i` is a placeholder for any key "
                "from Available Controls. Keys placed within one group "
                "press simultaneously. Within one `;`-separated group, "
                "each key may appear at most once. The same key repeated "
                "across consecutive groups extends the press across time. "
                "Up to 4 unique keys per group. Empty groups (`;`) are "
                "allowed."
            )
        else:
            key_header = (
                "Key Sequence: a single group of up to 4 unique keys "
                "(each `k_i` in the template is a placeholder for any key "
                "from Available Controls) to hold this step."
            )
        lines.append(f"{idx}. {key_header}")
        idx += 1
        if self.thinking:
            lines.append(
                f"{idx}. At most ONE sentence for your plan (no more). Then "
                "the action string on its own line."
            )
        else:
            lines.append(
                f"{idx}. Output the action string only; no commentary."
            )
        return "\n".join(lines)

    def _render_mouse_description(self) -> str:
        """One-line explanation of which mouse axes the VLM should emit."""
        phrases = {
            "X": (
                f"horizontal rotation `X` in degrees "
                f"(X>0 turn right)"
            ),
            "Y": (
                f"vertical rotation `Y` in degrees "
                f"(Y>0 look up)"
            ),
            "Z": "scroll `Z` (Z>0 scroll up)",
        }
        parts = [phrases[a] for a in self.mouse_axes if a in phrases]
        if not parts:
            return ""
        if len(parts) == 1:
            return parts[0] + "."
        return ", ".join(parts[:-1]) + ", and " + parts[-1] + "."

    def _keys_template(self, n: int) -> str:
        """Generate a `k1 k2 k3 ; k4 k5 ; ...` template with varying group sizes.

        The cycling pattern mimics the Lumine paper's example so the
        model sees that groups can hold multiple keys.
        """
        if n <= 0:
            return ""
        groups = []
        counter = 1
        for i in range(n):
            size = self._GROUP_SIZES[i % len(self._GROUP_SIZES)]
            group = " ".join(f"k{counter + j}" for j in range(size))
            counter += size
            groups.append(group)
        return " ; ".join(groups)

    # ── Compose + parse ───────────────────────────────────────────────

    def output_format(self, action_schema: dict) -> str:
        # Adapter is the source of truth for what actually executes;
        # overlay its chunk_steps and mouse_axes onto a local copy so
        # the rendered description and parser stay consistent.
        chunk = action_schema.get("chunk_steps") or self.chunk_steps
        step_ms = action_schema.get("step_duration_ms") or 33
        schema_axes = action_schema.get("mouse_axes")

        if schema_axes is not None and tuple(schema_axes) != self.mouse_axes:
            local = LumineStyle(
                name=self.name,
                thinking=self.thinking,
                mouse_axes=tuple(schema_axes),
                chunk_steps=self.chunk_steps,
            )
            return local.output_format(action_schema)

        parts = [
            self.render_pacing(chunk, step_ms),
            self.render_action_template(chunk),
            self.render_explanation(chunk),
        ]
        # Drop empty segments so a subclass returning "" for any render_*
        # doesn't leave a stray blank line in the system prompt.
        return "\n\n".join(p for p in parts if p)

    def per_turn_user_text(self) -> str:
        return USER_PROMPT

    def parse(self, response: str, *, action_schema: dict | None = None) -> dict | None:
        schema = action_schema or {}
        chunk_steps = schema.get("chunk_steps") or self.chunk_steps
        schema_axes = schema.get("mouse_axes")
        axes = tuple(schema_axes) if schema_axes is not None else self.mouse_axes
        return parse_chunked_action(
            response,
            chunk_steps=chunk_steps,
            mouse_axes=axes,
        )

    def noop_action(self, action_schema: dict) -> dict:
        steps = action_schema.get("chunk_steps") or self.chunk_steps
        axes = action_schema.get("mouse_axes")
        if axes is None:
            axes = self.mouse_axes
        return {
            "mouse": (0, 0, 0),
            "mouse_output": (0, 0, 0),
            "mouse_axes": tuple(axes),
            "steps": [[] for _ in range(steps)],
        }

    def compact_history_action(self, raw_response: str) -> str:
        """Past Lumine responses carry a 1-2 sentence plan before the
        action tag. Drop the plan and keep only the action tag so the
        packed-history block stays short.

        Same `[>}]` brace tolerance as the main parser regex above: when
        a past turn typo'd `<|action_start|}`, we still want history
        compaction to find and keep just the action tag rather than
        dumping the whole reasoning blob — otherwise the model sees its
        own broken tag verbatim and replays the typo on the next turn.
        """
        import re as _re
        match = _re.search(
            r'<\|action_start\|[>}].*?<\|action_end\|[>}]',
            raw_response or "",
            _re.DOTALL,
        )
        return match.group(0) if match else (raw_response or "").strip()


SPEC = LumineStyle()  # default: thinking=True, mouse=True, chunk_steps=8
