extends: vanilla_lfm.yaml

output_root: runs/lfm_variant/sky_duel/Var3
output_root_is_final: true

env:
  map: sky_duel_var3

players_defaults:
  game_prompt_key: variants/sky_duel_var3_player{player}

params:
  with_reasoning: true
  with_skill_prompt: false
